"""empty message

Revision ID: ac3dd62353b5
Revises: 48ce770b565a
Create Date: 2025-08-19 19:11:25.095067

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac3dd62353b5'
down_revision = '48ce770b565a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('character', schema=None) as batch_op:
        batch_op.drop_constraint('character_homeworld_id_fkey', type_='foreignkey')
        batch_op.drop_column('homeworld_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('character', schema=None) as batch_op:
        batch_op.add_column(sa.Column('homeworld_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('character_homeworld_id_fkey', 'planet', ['homeworld_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###
